name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch: # Requerido para Jira/API
    inputs:
      jira_issue_key:
        description: 'La clave de la incidencia de Jira'
        required: true
        type: string
  workflow_call: # Opcional: permite llamadas de otros workflows
    inputs:
      jira_issue_key:
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print static message
        run: echo "Hello, World! El disparador está activo."
      
      - name: Print Jira Issue Key
        run: echo "Received Jira Issue Key:${{ github.event.inputs.jira_issue_key || inputs.jira_issue_key }}"
